# Generated by Django 4.2 on 2025-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HearArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='hero_area')),
                ('icon_title', models.CharField(blank=True, max_length=20, null=True)),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='hero_area')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
