# Generated by Django 4.2 on 2025-06-09 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_service2_service3_service4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ReviewLeft')),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
