# Generated by Django 4.2 on 2025-06-11 04:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_review_reviewtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('aboutus', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=30)),
                ('phone', models.IntegerField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=50)),
            ],
        ),
    ]
